"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a5h&@dt)tiz8v#58f2ksv2++qiol28qod_$s1m7xynf0vke_cw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 静态文件
    'static',
    'libs',
    # 子应用的注册
    'users.apps.UsersConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],   # 设置模板路径
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# 数据库配置(默认为sqlite轻量型数据库，需要更改为MySQL)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",       # 数据库引擎
        "HOST": "127.0.0.1",                        # 数据库主机(或写为localhost)
        "PORT": 3306,                               # 数据库端口
        "USER": "myblog",                           # 数据库用户名
        "PASSWORD": "123456",                       # 数据库密码
        "NAME": "blog",                             # 数据库名字
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#设置静态资源的路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
]


# redis 配置信息(将session信息存储的数据库由默认sqlite存储更改为redis存储)
CACHES = {
    "default": {        # default 是缓存名，可以配置多个缓存
        # 应用django-redis库的RedisCache缓存类
        "BACKEND": "django_redis.cache.RedisCache",
        # 配置的网站ip和站点port
        "LOCATION": "redis://127.0.0.1:6379/0",  # redis的0号库是default的默认库
        "OPTIONS": {
            # redis客户端类
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
        # 如果redis设置了密码，那么需要设置对应的密码
        # "PASSWORD": "123456",
    },
    "session": {        # session
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # redis的1号库作为session信息存储位置
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}

# 配置session的引擎为cache，session由数据库存储更改为redis存储
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# 指定保存至redis的1号库
SESSION_CACHE_ALIAS = "session"



# 日志文件配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,    # 是否禁用已经存在的日志器
    'formatters': {         # 设置日志信息显示的格式
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s'
        },
    },
    'filters': {        # 对日志进行过滤
        'require_debug_true': {       # django在debug模式下才输出日志
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {      # 日志处理方法
            'console': {       # 向终端中输出日志
                'level': 'INFO',
                'filters': ['require_debug_true'],
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
            'file': {       # 向文件中输出日志
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': os.path.join(BASE_DIR,'blogs/blog.log'),  # 日志文件的位置,保存在blog/blog/blogs文件夹下
                'maxBytes': 300 * 1024 * 1024,
                'backupCount': 10,
                'formatter': 'verbose',
            },
        },
    'loggers': {        # 日志器
        'django': {     # 定义了一个名为django的日志器(后续通过名为django日志器)
            'handlers': ['console','file'],   # 可以同时向终端与文件中输出日志
            'propagate': True,                  # 是否继续传递日志信息
            'level': 'INFO',                    # 日志器接收的最低日志级别
        },
    },
}


#替换 系统的User 来使用我们自己定义的User
# 配置信息 为 ‘子应用名.模型类型’
AUTH_USER_MODEL='users.User'